series_index:
    path:     /series
    defaults: { _controller: EnbabyDBManagerBundle:Series:index }

series_info:
    path:     /series/id/{seriesId}
    defaults: { _controller: EnbabyDBManagerBundle:Series:series,seriesId:new }

series_update:
    path:     /series/update
    defaults: { _controller: EnbabyDBManagerBundle:Series:update }

series_snapshotupload:
    path:     /series/upload
    defaults: { _controller: EnbabyDBManagerBundle:Series:snapshotupload }

series_remove:
    path:     /series/remove
    defaults: { _controller: EnbabyDBManagerBundle:Series:remove }

books_index: 
    path:     /books
    defaults: { _controller: EnbabyDBManagerBundle:Books:index }

books_info:
    path:     /book/isbn/{isbn}
    defaults: { _controller: EnbabyDBManagerBundle:Books:book }

books_update: 
    path:     /book/update
    defaults: { _controller: EnbabyDBManagerBundle:Books:update }

books_remove: 
    path:     /book/remove
    defaults: { _controller: EnbabyDBManagerBundle:Books:remove }

books_audioupload:
    path:     /book/audioupload
    defaults: { _controller: EnbabyDBManagerBundle:Books:audioupload}

books_snapshotupload:
    path:     /book/snapshotupload
    defaults: { _controller: EnbabyDBManagerBundle:Books:snapshotupload }

