enbaby_db_audio_lib:
    resource: "@EnbabyDBAudioLibBundle/Resources/config/routing.yml"
    prefix:   /audiolib

enbaby_db_manager:
    resource: "@EnbabyDBManagerBundle/Resources/config/routing.yml"
    prefix:   /manager

#app:
#    resource: @AppBundle/Controller/
#    type:     annotation
